//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volvo.LAT.MVCWebUIComponent.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volvo.LAT.MVCWebUIComponent.App_LocalResources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this item?.
        /// </summary>
        public static string Action_Delete_Confirm {
            get {
                return ResourceManager.GetString("Action_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export {
            get {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Action_View {
            get {
                return ResourceManager.GetString("Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string Authorization_AccessDeniedLabel {
            get {
                return ResourceManager.GetString("Authorization_AccessDeniedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this content.
        ///Please contact service Administrator..
        /// </summary>
        public static string Authorization_AccessDeniedMessageLabel {
            get {
                return ResourceManager.GetString("Authorization_AccessDeniedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed..
        /// </summary>
        public static string Authorization_AuthFailedLabel {
            get {
                return ResourceManager.GetString("Authorization_AuthFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since your user id is not registered yet, you may not access some features of this application. To register your user id, please access the My Profile section..
        /// </summary>
        public static string Authorization_NotRegisteredUser {
            get {
                return ResourceManager.GetString("Authorization_NotRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page doesn&apos;t exist..
        /// </summary>
        public static string Error_404Message {
            get {
                return ResourceManager.GetString("Error_404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the system administrator for more details. Or send an e-mail to support.dotnet@volvo.com.&lt;br&gt;
        ///Error Id: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string Error_500Message {
            get {
                return ResourceManager.GetString("Error_500Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catastrophic Error!.
        /// </summary>
        public static string Error_Catastrophic {
            get {
                return ResourceManager.GetString("Error_Catastrophic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} must be {1} than {2}..
        /// </summary>
        public static string Error_CompareToValidator {
            get {
                return ResourceManager.GetString("Error_CompareToValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order already has an order row with the part {0}..
        /// </summary>
        public static string Error_CreateOrderRowPartExistent {
            get {
                return ResourceManager.GetString("Error_CreateOrderRowPartExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures are not configured in the application configuration file..
        /// </summary>
        public static string Error_CulturesNotConfigured {
            get {
                return ResourceManager.GetString("Error_CulturesNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some important resource is not available to run this application.
        /// </summary>
        public static string Error_ErrorImportantResourceTitle {
            get {
                return ResourceManager.GetString("Error_ErrorImportantResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Error_ErrorMessageLabel {
            get {
                return ResourceManager.GetString("Error_ErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some important resource is not available to run this application. 
        ///.
        /// </summary>
        public static string Error_ImportantResource {
            get {
                return ResourceManager.GetString("Error_ImportantResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is invalid..
        /// </summary>
        public static string Error_InvalidOrder {
            get {
                return ResourceManager.GetString("Error_InvalidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order row is invalid..
        /// </summary>
        public static string Error_InvalidOrderRow {
            get {
                return ResourceManager.GetString("Error_InvalidOrderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part is invalid..
        /// </summary>
        public static string Error_InvalidPart {
            get {
                return ResourceManager.GetString("Error_InvalidPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are not authorized to view this page or run the requested action..
        /// </summary>
        public static string Error_NotAuthorizedMessage {
            get {
                return ResourceManager.GetString("Error_NotAuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are not authorized to run this action or view this page..
        /// </summary>
        public static string Error_NotAuthorizedTitle {
            get {
                return ResourceManager.GetString("Error_NotAuthorizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0} could not be null..
        /// </summary>
        public static string Error_NullValue {
            get {
                return ResourceManager.GetString("Error_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date can&apos;t be earlier than order date..
        /// </summary>
        public static string Error_Order_DeliveryDateEarlier {
            get {
                return ResourceManager.GetString("Error_Order_DeliveryDateEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application generated an Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string Error_TryAgainLabel {
            get {
                return ResourceManager.GetString("Error_TryAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVS Example Application.
        /// </summary>
        public static string Layout_Legal {
            get {
                return ResourceManager.GetString("Layout_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVS Parts Ordering System.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS - NVS Example.
        /// </summary>
        public static string Layout_Version {
            get {
                return ResourceManager.GetString("Layout_Version", resourceCulture);
            }
        }
    }
}
