//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volvo.LAT.MVCWebUIComponent.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volvo.LAT.MVCWebUIComponent.App_LocalResources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Home_About_AboutLabel {
            get {
                return ResourceManager.GetString("Home_About_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Home_About_HelpLabel {
            get {
                return ResourceManager.GetString("Home_About_HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details how to code, performance, maintainability, naming, code design, etc..
        /// </summary>
        public static string Home_About_HowToStart_DetailsOnCoding {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_DetailsOnCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details how to start developing..
        /// </summary>
        public static string Home_About_HowToStart_DetailsToInitDev {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_DetailsToInitDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you know how to access it?.
        /// </summary>
        public static string Home_About_HowToStart_HowToAcces {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_HowToAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Home_About_HowToStart_Read {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the POS Getting Started at.
        /// </summary>
        public static string Home_About_HowToStart_ReadGettingStarted {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_ReadGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the POS source code at.
        /// </summary>
        public static string Home_About_HowToStart_SeeSourceCode {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_SeeSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour on POS application, register an Order, have fun!.
        /// </summary>
        public static string Home_About_HowToStart_TakeTour {
            get {
                return ResourceManager.GetString("Home_About_HowToStart_TakeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Start?.
        /// </summary>
        public static string Home_About_HowToStartTitle {
            get {
                return ResourceManager.GetString("Home_About_HowToStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details in.
        /// </summary>
        public static string Home_About_InfoLabel_MoreDetails {
            get {
                return ResourceManager.GetString("Home_About_InfoLabel_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS reference application..
        /// </summary>
        public static string Home_About_InfoLabel_PosRefApp {
            get {
                return ResourceManager.GetString("Home_About_InfoLabel_PosRefApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application functionality enables simple management of orders, such as: create, update and delete..
        /// </summary>
        public static string Home_About_IntroDesc_PosDesc_Func {
            get {
                return ResourceManager.GetString("Home_About_IntroDesc_PosDesc_Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s purpose is to show NVS architecture, design patterns and conventions implemented in practical, but.
        /// </summary>
        public static string Home_About_IntroDesc_PosDesc_Proposal {
            get {
                return ResourceManager.GetString("Home_About_IntroDesc_PosDesc_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simplified real-life scenario.
        /// </summary>
        public static string Home_About_IntroDesc_PosDesc_Proposal_Scenario {
            get {
                return ResourceManager.GetString("Home_About_IntroDesc_PosDesc_Proposal_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source solution may be also used as template for new projects..
        /// </summary>
        public static string Home_About_IntroDesc_PosDesc_SourceCode {
            get {
                return ResourceManager.GetString("Home_About_IntroDesc_PosDesc_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the NVS reference application example implementation..
        /// </summary>
        public static string Home_About_IntroDesc_WhatIsPos {
            get {
                return ResourceManager.GetString("Home_About_IntroDesc_WhatIsPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Home_About_IntroductionTitle {
            get {
                return ResourceManager.GetString("Home_About_IntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVS reference architecture:.
        /// </summary>
        public static string Home_About_References_NvsRefArch {
            get {
                return ResourceManager.GetString("Home_About_References_NvsRefArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telerik controls:.
        /// </summary>
        public static string Home_About_References_TelerikControls {
            get {
                return ResourceManager.GetString("Home_About_References_TelerikControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interfaces guidelines:.
        /// </summary>
        public static string Home_About_References_UserInterfaceGuides {
            get {
                return ResourceManager.GetString("Home_About_References_UserInterfaceGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string Home_About_ReferencesTitle {
            get {
                return ResourceManager.GetString("Home_About_ReferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS application presents a fictitious business process. This application is not necessarily designed to demonstrate the Volvo process for part management. The focus of POS is to demonstrate application logic, not user interaction..
        /// </summary>
        public static string Home_About_RequirementsUsability_PosFocus {
            get {
                return ResourceManager.GetString("Home_About_RequirementsUsability_PosFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you start a project remember to meet with end-users to elicit requirements and find the way of working..
        /// </summary>
        public static string Home_About_RequirementsUsability_TalkToUsers {
            get {
                return ResourceManager.GetString("Home_About_RequirementsUsability_TalkToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use prototyping and user evaluation to reach a common understanding and properly set expectations..
        /// </summary>
        public static string Home_About_RequirementsUsability_UsePrototype {
            get {
                return ResourceManager.GetString("Home_About_RequirementsUsability_UsePrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ensure that the user interaction is implemented efficiently for the end-users..
        /// </summary>
        public static string Home_About_RequirementsUsability_UserInteraction {
            get {
                return ResourceManager.GetString("Home_About_RequirementsUsability_UserInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes about Requirements and Usability.
        /// </summary>
        public static string Home_About_RequirementsUsabilityTitle {
            get {
                return ResourceManager.GetString("Home_About_RequirementsUsabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string Home_Index_Header {
            get {
                return ResourceManager.GetString("Home_Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information about this application.
        /// </summary>
        public static string Home_Index_MoreInfo {
            get {
                return ResourceManager.GetString("Home_Index_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAT - Home Page.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
    }
}
