//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volvo.LAT.MVCWebUIComponent.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JavascriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavascriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volvo.LAT.MVCWebUIComponent.App_LocalResources.JavascriptResource", typeof(JavascriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will lose all inputted data. Do you want to proceed?.
        /// </summary>
        public static string Action_BackConfirm {
            get {
                return ResourceManager.GetString("Action_BackConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will lose all inputted data. Do you want to proceed?.
        /// </summary>
        public static string Action_CloseConfirm {
            get {
                return ResourceManager.GetString("Action_CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this item?.
        /// </summary>
        public static string Action_DeleteConfirm {
            get {
                return ResourceManager.GetString("Action_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Action_Deleting {
            get {
                return ResourceManager.GetString("Action_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server raised the following error when requested: .
        /// </summary>
        public static string Error_Ajax {
            get {
                return ResourceManager.GetString("Error_Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is unauthorized by your user..
        /// </summary>
        public static string Error_Ajax_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Ajax_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while trying to communicate with the server.
        /// </summary>
        public static string Error_GenericAjax {
            get {
                return ResourceManager.GetString("Error_GenericAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .messageContainer was not found..
        /// </summary>
        public static string Error_MessageContainerNotFound {
            get {
                return ResourceManager.GetString("Error_MessageContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have added the selected part..
        /// </summary>
        public static string Error_OrderRowRequestedPartValidation {
            get {
                return ResourceManager.GetString("Error_OrderRowRequestedPartValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be bigger than available amount in Part..
        /// </summary>
        public static string Error_OrderRowRequestedQuantityRangeValidation {
            get {
                return ResourceManager.GetString("Error_OrderRowRequestedQuantityRangeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is not available because you don&apos;t have access, no order is selected or the action is not applicable for the current order.
        /// </summary>
        public static string Order_Action_DisabledTooltip {
            get {
                return ResourceManager.GetString("Order_Action_DisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action could not be performed. Please try again later.
        /// </summary>
        public static string Order_ActionError {
            get {
                return ResourceManager.GetString("Order_ActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current order?.
        /// </summary>
        public static string Order_CancelOrder {
            get {
                return ResourceManager.GetString("Order_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order could not be cancelled.
        /// </summary>
        public static string Order_TrackOrders_CancelError {
            get {
                return ResourceManager.GetString("Order_TrackOrders_CancelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Order_TrackOrders_Cancelling {
            get {
                return ResourceManager.GetString("Order_TrackOrders_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel selected Order..
        /// </summary>
        public static string Order_TrackOrders_CancelOrderButtonTooltip {
            get {
                return ResourceManager.GetString("Order_TrackOrders_CancelOrderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming....
        /// </summary>
        public static string Order_TrackOrders_Confirming {
            get {
                return ResourceManager.GetString("Order_TrackOrders_Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm selected Order..
        /// </summary>
        public static string Order_TrackOrders_ConfirmOrderButtonTooltip {
            get {
                return ResourceManager.GetString("Order_TrackOrders_ConfirmOrderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View selected Order..
        /// </summary>
        public static string Order_TrackOrders_ViewOrderButtonTooltip {
            get {
                return ResourceManager.GetString("Order_TrackOrders_ViewOrderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0} added to cart..
        /// </summary>
        public static string Part_SearchParts_AddedPart {
            get {
                return ResourceManager.GetString("Part_SearchParts_AddedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased quantity for Part {0}..
        /// </summary>
        public static string Part_SearchParts_AddedQuantity {
            get {
                return ResourceManager.GetString("Part_SearchParts_AddedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a part to be added.
        /// </summary>
        public static string Part_SearchParts_AddToCart_ButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("Part_SearchParts_AddToCart_ButtonDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected Part to the shopping cart.
        /// </summary>
        public static string Part_SearchParts_AddToCartButtonTooltip {
            get {
                return ResourceManager.GetString("Part_SearchParts_AddToCartButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Reports_Export {
            get {
                return ResourceManager.GetString("Reports_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string Reports_GoToFirstPage {
            get {
                return ResourceManager.GetString("Reports_GoToFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string Reports_GoToLastPage {
            get {
                return ResourceManager.GetString("Reports_GoToLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Reports_GoToNextPage {
            get {
                return ResourceManager.GetString("Reports_GoToNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Reports_GoToPrevPage {
            get {
                return ResourceManager.GetString("Reports_GoToPrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Backward.
        /// </summary>
        public static string Reports_HistoryBack {
            get {
                return ResourceManager.GetString("Reports_HistoryBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Forward.
        /// </summary>
        public static string Reports_HistoryForward {
            get {
                return ResourceManager.GetString("Reports_HistoryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Reports_Preview {
            get {
                return ResourceManager.GetString("Reports_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string Reports_Print {
            get {
                return ResourceManager.GetString("Reports_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Reports_Refresh {
            get {
                return ResourceManager.GetString("Reports_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Document Map.
        /// </summary>
        public static string Reports_ToggleDocumentMap {
            get {
                return ResourceManager.GetString("Reports_ToggleDocumentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Parameters Area.
        /// </summary>
        public static string Reports_ToggleParametersArea {
            get {
                return ResourceManager.GetString("Reports_ToggleParametersArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Print Preview.
        /// </summary>
        public static string Reports_TogglePrintPreview {
            get {
                return ResourceManager.GetString("Reports_TogglePrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Side Menu.
        /// </summary>
        public static string Reports_ToggleSideMenu {
            get {
                return ResourceManager.GetString("Reports_ToggleSideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle FullPage/PageWidth.
        /// </summary>
        public static string Reports_ToggleZoomMode {
            get {
                return ResourceManager.GetString("Reports_ToggleZoomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string Reports_ZoomIn {
            get {
                return ResourceManager.GetString("Reports_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string Reports_ZoomOut {
            get {
                return ResourceManager.GetString("Reports_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current Order.
        /// </summary>
        public static string ShoppingCart_CancelButtonTootltip {
            get {
                return ResourceManager.GetString("ShoppingCart_CancelButtonTootltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart (Empty).
        /// </summary>
        public static string ShoppingCart_Cart_Empty {
            get {
                return ResourceManager.GetString("ShoppingCart_Cart_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart ({0} items - {1} SEK).
        /// </summary>
        public static string ShoppingCart_Cart_ManyItems {
            get {
                return ResourceManager.GetString("ShoppingCart_Cart_ManyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart (1 item - {0} SEK).
        /// </summary>
        public static string ShoppingCart_Cart_OneItem {
            get {
                return ResourceManager.GetString("ShoppingCart_Cart_OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action is possible as there are no items in the cart.
        /// </summary>
        public static string ShoppingCart_CheckOutButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("ShoppingCart_CheckOutButtonDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks out the cart items.
        /// </summary>
        public static string ShoppingCart_CheckOutButtonTooltip {
            get {
                return ResourceManager.GetString("ShoppingCart_CheckOutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to clear all items from the Shopping Cart?.
        /// </summary>
        public static string ShoppingCart_ClearAllItems {
            get {
                return ResourceManager.GetString("ShoppingCart_ClearAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action is disabled because you need to select a cart item.
        /// </summary>
        public static string ShoppingCart_DeleteButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("ShoppingCart_DeleteButtonDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a selected shopping cart item.
        /// </summary>
        public static string ShoppingCart_DeleteButtonTooltip {
            get {
                return ResourceManager.GetString("ShoppingCart_DeleteButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string User_AddEditUser_CancelButtonTooltip {
            get {
                return ResourceManager.GetString("User_AddEditUser_CancelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user..
        /// </summary>
        public static string User_ManageUsers_AddUserButtonTooltip {
            get {
                return ResourceManager.GetString("User_ManageUsers_AddUserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button is disabled because you need to select some user!.
        /// </summary>
        public static string User_ManageUsers_ButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("User_ManageUsers_ButtonDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected user..
        /// </summary>
        public static string User_ManageUsers_DeleteUserButtonTooltip {
            get {
                return ResourceManager.GetString("User_ManageUsers_DeleteUserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected user..
        /// </summary>
        public static string User_ManageUsers_EditUserButtonTooltip {
            get {
                return ResourceManager.GetString("User_ManageUsers_EditUserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button is disabled because you need to select some order!.
        /// </summary>
        public static string User_TrackOrders_ButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("User_TrackOrders_ButtonDisabledTooltip", resourceCulture);
            }
        }
    }
}
