//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volvo.LAT.MVCWebUIComponent.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volvo.LAT.MVCWebUIComponent.App_LocalResources.UtilityResource", typeof(UtilityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PanelBar.
        /// </summary>
        public static string Utilites_CSSOverview_PanelBar {
            get {
                return ResourceManager.GetString("Utilites_CSSOverview_PanelBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Overview.
        /// </summary>
        public static string Utilities_CSSOverview {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Utilities_CSSOverview_Action {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another one.
        /// </summary>
        public static string Utilities_CSSOverview_AnotherButton {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_AnotherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burglaries per 100,000 population.
        /// </summary>
        public static string Utilities_CSSOverview_BurglariesPerPopulation {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_BurglariesPerPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Utilities_CSSOverview_Button {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid car mileage report.
        /// </summary>
        public static string Utilities_CSSOverview_CarReport {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_CarReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        public static string Utilities_CSSOverview_Checkbox {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled checkbox.
        /// </summary>
        public static string Utilities_CSSOverview_CheckboxDis {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_CheckboxDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes and Radio buttons.
        /// </summary>
        public static string Utilities_CSSOverview_CheckboxTitle {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_CheckboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Utilities_CSSOverview_Checked {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Area.
        /// </summary>
        public static string Utilities_CSSOverview_CommandArea {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_CommandArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime statistics.
        /// </summary>
        public static string Utilities_CSSOverview_CrimeStatistics {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_CrimeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Utilities_CSSOverview_Day {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Utilities_CSSOverview_Disabled {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Utilities_CSSOverview_Editor {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Utilities_CSSOverview_Enabled {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Utilities_CSSOverview_Error {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first panel.
        /// </summary>
        public static string Utilities_CSSOverview_FirstPanel {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_FirstPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first tab.
        /// </summary>
        public static string Utilities_CSSOverview_FirstTab {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_FirstTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Utilities_CSSOverview_Grid {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Utilities_CSSOverview_GridCountry {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_GridCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some value.
        /// </summary>
        public static string Utilities_CSSOverview_GridValue {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_GridValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Utilities_CSSOverview_GridYear {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_GridYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Utilities_CSSOverview_Group {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Header.
        /// </summary>
        public static string Utilities_CSSOverview_GroupHeader {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Utilities_CSSOverview_Header {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Utilities_CSSOverview_Headers {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover here....
        /// </summary>
        public static string Utilities_CSSOverview_HoverHere {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_HoverHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydro.
        /// </summary>
        public static string Utilities_CSSOverview_Hydro {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Hydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Utilities_CSSOverview_Information {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Users.
        /// </summary>
        public static string Utilities_CSSOverview_InternetUsers {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_InternetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just text.
        /// </summary>
        public static string Utilities_CSSOverview_JustText {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_JustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left pane.
        /// </summary>
        public static string Utilities_CSSOverview_LeftPane {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_LeftPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Utilities_CSSOverview_Link {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Utilities_CSSOverview_List {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Utilities_CSSOverview_List_Item {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_List_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Utilities_CSSOverview_Menu {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beds.
        /// </summary>
        public static string Utilities_CSSOverview_MenuBeds {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Utilities_CSSOverview_MenuBlog {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpets.
        /// </summary>
        public static string Utilities_CSSOverview_MenuCarpets {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuCarpets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Furniture.
        /// </summary>
        public static string Utilities_CSSOverview_MenuChildren {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Utilities_CSSOverview_MenuCompany {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtains &amp; Blinds.
        /// </summary>
        public static string Utilities_CSSOverview_MenuCurtains {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuCurtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decor.
        /// </summary>
        public static string Utilities_CSSOverview_MenuDecor {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuDecor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string Utilities_CSSOverview_MenuFurniture {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Linen.
        /// </summary>
        public static string Utilities_CSSOverview_MenuLinen {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuLinen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Utilities_CSSOverview_MenuNews {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasional Furniture.
        /// </summary>
        public static string Utilities_CSSOverview_MenuOccasional {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuOccasional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Utilities_CSSOverview_MenuProducts {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugs.
        /// </summary>
        public static string Utilities_CSSOverview_MenuRugs {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuRugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofas.
        /// </summary>
        public static string Utilities_CSSOverview_MenuSofas {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuSofas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables &amp; Chairs.
        /// </summary>
        public static string Utilities_CSSOverview_MenuTables {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws.
        /// </summary>
        public static string Utilities_CSSOverview_MenuThrows {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MenuThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select a country..
        /// </summary>
        public static string Utilities_CSSOverview_MultiSelectPlaceHolder {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MultiSelectPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murders per 100,000 population.
        /// </summary>
        public static string Utilities_CSSOverview_MurdersPerPopulation {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_MurdersPerPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Utilities_CSSOverview_Notifications {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear.
        /// </summary>
        public static string Utilities_CSSOverview_Nuclear {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Nuclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open window.
        /// </summary>
        public static string Utilities_CSSOverview_OpenWindow {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Communication {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Forecast {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Forecasts.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Forecasts {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Forecasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Friday {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Monday {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Business Plan.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_NewPlan {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_NewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Programs {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Projects {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Reports.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Reports {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Thursday {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Tuesday {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Utilities_CSSOverview_PanelBar_Wednesday {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PanelBar_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Utilities_CSSOverview_Password {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled password.
        /// </summary>
        public static string Utilities_CSSOverview_PasswordDis {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_PasswordDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickers.
        /// </summary>
        public static string Utilities_CSSOverview_Pickers {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Pickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value....
        /// </summary>
        public static string Utilities_CSSOverview_Pickers_EnterValue {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Pickers_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select countries....
        /// </summary>
        public static string Utilities_CSSOverview_Pickers_SelectCountries {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Pickers_SelectCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country....
        /// </summary>
        public static string Utilities_CSSOverview_Pickers_SelectCountry {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Pickers_SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bar.
        /// </summary>
        public static string Utilities_CSSOverview_ProgressBar {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton.
        /// </summary>
        public static string Utilities_CSSOverview_RadioButton {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled radioButton.
        /// </summary>
        public static string Utilities_CSSOverview_RadioButtonDis {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_RadioButtonDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right pane.
        /// </summary>
        public static string Utilities_CSSOverview_RightPane {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_RightPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample content.
        /// </summary>
        public static string Utilities_CSSOverview_SampleContent {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_SampleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second panel.
        /// </summary>
        public static string Utilities_CSSOverview_SecondPanel {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_SecondPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second tab.
        /// </summary>
        public static string Utilities_CSSOverview_SecondTab {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_SecondTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Utilities_CSSOverview_Slider {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        public static string Utilities_CSSOverview_Solar {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Solar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break-up of Spain Electricity Production for 2008.
        /// </summary>
        public static string Utilities_CSSOverview_SpainElectricity {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_SpainElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        public static string Utilities_CSSOverview_Splitter {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Utilities_CSSOverview_Success {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Utilities_CSSOverview_Table {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Utilities_CSSOverview_Table_Column {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Table_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Utilities_CSSOverview_Table_Footer {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Table_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabStrip.
        /// </summary>
        public static string Utilities_CSSOverview_TabStrip {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TabStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextArea.
        /// </summary>
        public static string Utilities_CSSOverview_TextArea {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled textArea.
        /// </summary>
        public static string Utilities_CSSOverview_TextAreaDis {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TextAreaDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        public static string Utilities_CSSOverview_TextBox {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled textBox.
        /// </summary>
        public static string Utilities_CSSOverview_TextBoxDis {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TextBoxDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third panel.
        /// </summary>
        public static string Utilities_CSSOverview_ThirdPanel {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_ThirdPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third tab.
        /// </summary>
        public static string Utilities_CSSOverview_ThirdTab {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_ThirdTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        public static string Utilities_CSSOverview_Toolbar {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        public static string Utilities_CSSOverview_Tooltip {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover me.
        /// </summary>
        public static string Utilities_CSSOverview_ToolTipTitle {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView.
        /// </summary>
        public static string Utilities_CSSOverview_TreeView {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United states.
        /// </summary>
        public static string Utilities_CSSOverview_USA {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Utilities_CSSOverview_Warning {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string Utilities_CSSOverview_Wind {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Utilities_CSSOverview_Window {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string Utilities_CSSOverview_World {
            get {
                return ResourceManager.GetString("Utilities_CSSOverview_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundling and Minification has been disabled..
        /// </summary>
        public static string Utilities_EnableBundlingAndMinification_Disabled {
            get {
                return ResourceManager.GetString("Utilities_EnableBundlingAndMinification_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundling and Minification has been enabled..
        /// </summary>
        public static string Utilities_EnableBundlingAndMinification_Enabled {
            get {
                return ResourceManager.GetString("Utilities_EnableBundlingAndMinification_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Tests for POS Javascript Code.
        /// </summary>
        public static string Utilities_JavascriptUnitTests_Title {
            get {
                return ResourceManager.GetString("Utilities_JavascriptUnitTests_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization has been changed to {0}..
        /// </summary>
        public static string Utilities_SetLocalization_LocalizationHasBeenChanged {
            get {
                return ResourceManager.GetString("Utilities_SetLocalization_LocalizationHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand has been changed to {0}..
        /// </summary>
        public static string Utilities_SetTheme_BrandHasBeenChanged {
            get {
                return ResourceManager.GetString("Utilities_SetTheme_BrandHasBeenChanged", resourceCulture);
            }
        }
    }
}
