//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Volvo.POS.Proxy.Warehouse.RequestReply.Contracts {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PartReservationRequest {
        
        private PartReservationRequestPart[] orderRowsField;
        
        private string orderNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Part", IsNullable=false)]
        public PartReservationRequestPart[] OrderRows {
            get {
                return this.orderRowsField;
            }
            set {
                this.orderRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PartReservationRequestPart {
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        private decimal requestedQuantityField;
        
        private bool requestedQuantityFieldSpecified;
        
        /// <remarks/>
        public long Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal RequestedQuantity {
            get {
                return this.requestedQuantityField;
            }
            set {
                this.requestedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestedQuantitySpecified {
            get {
                return this.requestedQuantityFieldSpecified;
            }
            set {
                this.requestedQuantityFieldSpecified = value;
            }
        }
    }
}
